[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "profileforge"
version = "1.0.0"
authors = [
  { name="Gaurav Verma", email="gauravv2504@gmail.com" },
]
description = "The Open-Source GitHub Profile Engine"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "PyYAML>=6.0",
]

[tool.setuptools.package-data]
profileforge = [
    "themes/*.yaml",
    "templates/*/*.yaml",
    "templates/*/*.md",
    "templates/*/config/*.yaml",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
    "black>=24.0",
    "ruff>=0.3.0"
]
github = [
    "httpx>=0.28"
]

[project.scripts]
profileforge = "profileforge.cli.main:main"

[tool.black]
target-version = ['py39']
line-length = 88

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.pytest.ini_options]
testpaths = ["tests"]
