import argparse
import os
import sys
from pathlib import Path

# Ensure registries populate via side-effects
import profileforge.datasources.local
import profileforge.widgets.expertise
import profileforge.widgets.focus
import profileforge.widgets.roadmap  # noqa: F401

# Ensure registries populate
from profileforge.core.config import ConfigLoader
from profileforge.core.context import BuildContext, Services
from profileforge.core.exceptions import ProfileForgeError
from profileforge.core.registry import DATASOURCE_REGISTRY, WIDGET_REGISTRY
from profileforge.render.layout import LayoutEngine
from profileforge.render.svg.renderer import SVGRenderer


def print_success(msg: str):
    print(f"  + {msg}")


def print_error(msg: str):
    print(f"\nError: {msg}\n")


def cmd_build(args):
    config_path = Path(args.config)
    try:
        config = ConfigLoader.load_main_config(str(config_path))
        print_success("Loaded configuration")

        theme_dir = config_path.parent / "themes"
        theme = ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
        print_success(f'Loaded theme \\"{theme.name}\\"')

        datasources = {}
        for name, ds_config in config.datasources_config.items():
            if name in DATASOURCE_REGISTRY:
                # adjust relative path
                if "root" in ds_config:
                    ds_config["root"] = str(config_path.parent / ds_config["root"])
                datasources[name] = DATASOURCE_REGISTRY[name](ds_config)

        services = Services(datasources=datasources)
        context = BuildContext(theme=theme, config=config, services=services)
        svg_renderer = SVGRenderer(context)

        out_dir = (
            Path(args.output)
            if args.output
            else config_path.parent / config.outputs.svg.dir
        )
        out_dir.mkdir(parents=True, exist_ok=True)

        print_success(f"Registered {len(config.widgets)} widgets")

        # Load layout registry if dashboard is enabled
        from profileforge.dashboard.models import Dashboard, DashboardItem
        from profileforge.layouts.registry import LAYOUT_REGISTRY

        if config.dashboard.enabled:
            dashboard_items = []
            for w_config in config.widgets:
                if w_config.name not in WIDGET_REGISTRY:
                    print(f"  - Warning: Widget '{w_config.name}' not found. Skipping.")
                    continue
                widget = WIDGET_REGISTRY[w_config.name]()
                dashboard_items.append(DashboardItem(widget=widget, grid=w_config.grid))

            dashboard = Dashboard(
                title=config.dashboard.title,
                subtitle=config.dashboard.subtitle,
                items=dashboard_items,
                header=config.dashboard.header,
                footer=config.dashboard.footer,
            )

            layout_name = config.dashboard.layout
            if layout_name not in LAYOUT_REGISTRY:
                print_error(f"Layout '{layout_name}' not found in registry.")
                sys.exit(1)

            layout_strategy = LAYOUT_REGISTRY[layout_name]()
            component_tree = layout_strategy.compose(dashboard, context)

            # Since layout strategy returns a component tree, calculate its dimensions
            LayoutEngine.calculate(component_tree)

            if config.outputs.svg.enabled:
                svg_content = svg_renderer.render(component_tree)
                header = f"<!--\nGenerated by ProfileForge (Dashboard Engine)\nVersion: {config.version}\nTheme: {theme.name}\nLayout: {layout_name}\n-->\n"

                out_file = out_dir / "dashboard.svg"
                with open(out_file, "w", encoding="utf-8") as f:
                    f.write(header + svg_content)
                print_success("Generated dashboard.svg")
        else:
            # Legacy individual widget rendering
            for w_config in config.widgets:
                if w_config.name not in WIDGET_REGISTRY:
                    print(f"  - Warning: Widget '{w_config.name}' not found. Skipping.")
                    continue

                widget = WIDGET_REGISTRY[w_config.name]()
                component_tree = widget.build(context)
                LayoutEngine.calculate(component_tree)

                if config.outputs.svg.enabled:
                    svg_content = svg_renderer.render(component_tree)
                    header = f"<!--\nGenerated by ProfileForge\nVersion: {config.version}\nTheme: {theme.name}\n-->\n"

                    out_file = out_dir / f"{w_config.name}.svg"
                    with open(out_file, "w", encoding="utf-8") as f:
                        f.write(header + svg_content)
                    print_success(f"Generated {w_config.name}.svg")

        print("\nDone.")
    except ProfileForgeError as e:
        print_error(str(e))
        sys.exit(1)


def cmd_doctor(args):
    print("Running ProfileForge diagnostics...\n")
    print(f"  + Python version: {sys.version.split()[0]}")

    config_path = Path("profileforge.yaml")
    if config_path.exists():
        print_success("profileforge.yaml found")
        try:
            config = ConfigLoader.load_main_config(str(config_path))
            print_success("Configuration parsed successfully")

            theme_dir = config_path.parent / "themes"
            ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
            print_success("Theme loaded successfully")
        except ProfileForgeError as e:
            print_error(f"Config/Theme error: {e}")
    else:
        print("  - profileforge.yaml NOT found in current directory")

    print_success(f"Widgets registered: {list(WIDGET_REGISTRY.keys())}")
    print_success(f"DataSources registered: {list(DATASOURCE_REGISTRY.keys())}")
    print("\nDiagnostics complete.")


def cmd_validate(args):
    config_path = Path(args.config)
    print(f"Validating configuration at '{config_path}'...\n")

    if not config_path.exists():
        print_error(f"Configuration file '{config_path}' not found.")
        sys.exit(1)

    try:
        config = ConfigLoader.load_main_config(str(config_path))
        print_success("profileforge.yaml valid")

        theme_dir = config_path.parent / "themes"
        ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
        print_success(f'Theme "{config.active_theme}" exists')

        for w in config.widgets:
            if w.name in WIDGET_REGISTRY:
                print_success(f'Widget "{w.name}"')
            else:
                print(f'  X Widget "{w.name}"')
                print("\nReason:\nUnknown widget")
                print(
                    "\nDid you mean:\n" + "\n".join([f"• {k}" for k in WIDGET_REGISTRY])
                )
                sys.exit(1)

        out_dir = (
            Path(args.output)
            if args.output
            else config_path.parent / config.outputs.svg.dir
        )
        if not out_dir.exists():
            out_dir.mkdir(parents=True, exist_ok=True)
        if os.access(out_dir, os.W_OK):
            print_success("Output directory writable")
        else:
            print_error(f"Output directory '{out_dir}' is not writable.")
            sys.exit(1)

        print("\nConfiguration is 100% valid.")
    except ProfileForgeError as e:
        print_error(str(e))
        sys.exit(1)


def cmd_new(args):
    target = Path(args.name)
    if target.exists():
        print_error(f"Directory '{args.name}' already exists.")
        sys.exit(1)

    target.mkdir()
    (target / "config").mkdir()
    (target / "themes").mkdir()
    (target / "assets").mkdir()

    with open(target / "profileforge.yaml", "w") as f:
        f.write("""version: 1
project:
  name: "New Profile"
themes:
  active: "github-dark"
datasources:
  local:
    root: "./config"
widgets: []
outputs:
  svg:
    enabled: true
    dir: "assets"
""")

    with open(target / "themes" / "github-dark.yaml", "w") as f:
        f.write("""name: github-dark
background: "#0D1117"
primary: "#58A6FF"
text: "#C9D1D9"
""")

    print_success(f"Created new ProfileForge project in '{args.name}'")
    print(f"\nRun 'cd {args.name}' then 'profileforge build' to get started.")


def main():
    parser = argparse.ArgumentParser(
        description="ProfileForge: Open-Source GitHub Profile Engine"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Build the profile widgets")
    build_parser.add_argument(
        "--config", default="profileforge.yaml", help="Path to config file"
    )
    build_parser.add_argument(
        "--output", default=None, help="Override output directory"
    )

    subparsers.add_parser("doctor", help="Check dependencies and environment")

    new_parser = subparsers.add_parser(
        "new", help="Scaffold a new ProfileForge project"
    )
    new_parser.add_argument("name", help="Name of the new project directory")

    validate_parser = subparsers.add_parser(
        "validate", help="Validate a configuration file"
    )
    validate_parser.add_argument(
        "--config", default="profileforge.yaml", help="Path to config file"
    )
    validate_parser.add_argument(
        "--output", default=None, help="Output directory to check write access"
    )

    args = parser.parse_args()

    if args.command == "build":
        cmd_build(args)
    elif args.command == "doctor":
        cmd_doctor(args)
    elif args.command == "validate":
        cmd_validate(args)
    elif args.command == "new":
        cmd_new(args)
    else:
        print_error(f"Command '{args.command}' is not implemented.")
        sys.exit(1)


if __name__ == "__main__":
    main()
