links:
  - platform: "github"
    url: "https://github.com/iisgaurav"
    handle: "iisgaurav"
  - platform: "twitter"
    url: "https://twitter.com/iisgaurav"
    handle: "iisgaurav"
  - platform: "instagram"
    url: "https://instagram.com/iisgaurav"
    handle: "iisgaurav"
  - platform: "npm"
    url: "https://www.npmjs.com/~iisgaurav"
    handle: "iisgaurav"
  - platform: "website"
    url: "https://iisgaurav.vercel.app"
    handle: "iisgaurav.vercel.app"
