import argparse
import os
import sys
from pathlib import Path

import profileforge.connectors.github.connector

# Ensure registries populate via side-effects
import profileforge.connectors.local
import profileforge.widgets.about
import profileforge.widgets.experience
import profileforge.widgets.expertise
import profileforge.widgets.focus
import profileforge.widgets.github_languages
import profileforge.widgets.github_stats
import profileforge.widgets.hero
import profileforge.widgets.now
import profileforge.widgets.repositories
import profileforge.widgets.roadmap
import profileforge.widgets.skills
import profileforge.widgets.social  # noqa: F401

# Ensure registries populate
from profileforge.core.config import ConfigLoader
from profileforge.core.context import BuildContext, Services
from profileforge.core.exceptions import ProfileForgeError
from profileforge.core.registry import WIDGET_REGISTRY, ConnectorRegistry
from profileforge.render.layout import LayoutEngine
from profileforge.render.svg.renderer import SVGRenderer
from profileforge.templates import (
    get_template_info,
    list_builtin_templates,
    scaffold_template,
)


def print_success(msg: str):
    print(f"  + {msg}")


def print_error(msg: str):
    print(f"\nError: {msg}\n")


def cmd_build(args):
    config_path = Path(args.config)
    try:
        config = ConfigLoader.load_main_config(str(config_path))
        print_success("Loaded configuration")

        theme_dir = config_path.parent / "themes"
        theme = ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
        print_success(f'Loaded theme \\"{theme.name}\\"')

        connectors = {}
        for name, ds_config in config.connectors_config.items():
            if name in ConnectorRegistry:
                # adjust relative path
                if "root" in ds_config:
                    ds_config["root"] = str(config_path.parent / ds_config["root"])
                connectors[name] = ConnectorRegistry[name](ds_config)

        services = Services(connectors=connectors)
        context = BuildContext(theme=theme, config=config, services=services)
        svg_renderer = SVGRenderer(context)

        out_dir = (
            Path(args.output)
            if args.output
            else config_path.parent / config.outputs.svg.dir
        )
        out_dir.mkdir(parents=True, exist_ok=True)

        print_success(f"Registered {len(config.widgets)} widgets")

        # Generate standalone SVGs for all widgets
        if config.outputs.svg.enabled:
            import html as html_mod

            defs_block = svg_renderer.get_defs()

        for w_config in config.widgets:
            if w_config.name not in WIDGET_REGISTRY:
                print(f"  - Warning: Widget '{w_config.name}' not found. Skipping.")
                continue

            widget = WIDGET_REGISTRY[w_config.name]()
            component_tree = widget.render_safe(context)
            LayoutEngine.calculate(component_tree)

            if config.outputs.svg.enabled:
                inner_svg = svg_renderer.render(component_tree)
                total_w = component_tree.computed_width
                total_h = component_tree.computed_height
                escaped_title = html_mod.escape(w_config.name.title())

                svg_content = (
                    f'<svg width="{total_w}" height="{total_h}" '
                    f'viewBox="0 0 {total_w} {total_h}" '
                    f'xmlns="http://www.w3.org/2000/svg" '
                    f'role="img">\n'
                    f"  <title>{escaped_title} Widget</title>\n"
                    f"  <desc>ProfileForge {escaped_title} widget</desc>\n"
                    f"  {defs_block}\n"
                    f"  {inner_svg}\n"
                    f"</svg>"
                )

                header = f"<!--\nGenerated by ProfileForge (Widget Engine)\nVersion: {config.version}\nTheme: {theme.name}\nWidget: {w_config.name}\n-->\n"

                out_file = out_dir / f"{w_config.name}.svg"
                with open(out_file, "w", encoding="utf-8") as f:
                    f.write(header + svg_content)
                print_success(f"Generated {w_config.name}.svg")

        print("\nDone.")
    except ProfileForgeError as e:
        print_error(str(e))
        sys.exit(1)


def cmd_doctor(args):
    print("Running ProfileForge diagnostics...\n")
    print(f"  + Python version: {sys.version.split()[0]}")

    config_path = Path("profileforge.yaml")
    if config_path.exists():
        print_success("profileforge.yaml found")
        try:
            config = ConfigLoader.load_main_config(str(config_path))
            print_success("Configuration parsed successfully")

            theme_dir = config_path.parent / "themes"
            ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
            print_success(f"Active theme '{config.active_theme}' loaded successfully")

            if theme_dir.exists():
                valid_themes = 0
                for theme_file in theme_dir.glob("*.yaml"):
                    try:
                        theme = ConfigLoader.load_theme(
                            theme_file.stem, themes_dir=str(theme_dir)
                        )
                        valid_themes += 1
                        meta_ok = bool(theme.id and theme.schema and theme.tags)
                        tokens_ok = bool(
                            theme.colors and theme.typography and theme.spacing
                        )
                        inherits = theme.extends if theme.extends else "None"
                        print_success(
                            f"Theme '{theme.name}': Metadata {'OK' if meta_ok else 'MISSING'}, Tokens {'OK' if tokens_ok else 'MISSING'}, Inheritance: {inherits}"
                        )
                    except Exception as e:
                        print_error(f"Failed to load theme {theme_file.name}: {e}")
                print_success(f"Validated {valid_themes} themes in {theme_dir}")
        except ProfileForgeError as e:
            print_error(f"Config/Theme error: {e}")
    else:
        print("  - profileforge.yaml NOT found in current directory")

    print_success(f"Widgets registered: {list(WIDGET_REGISTRY.keys())}")
    print_success(f"Connectors registered: {list(ConnectorRegistry.keys())}")

    builtin_themes_dir = Path(__file__).parent.parent / "themes"
    if builtin_themes_dir.exists():
        valid_builtin = 0
        for theme_file in builtin_themes_dir.glob("*.yaml"):
            try:
                theme = ConfigLoader.load_theme(
                    theme_file.stem, themes_dir=str(builtin_themes_dir)
                )
                valid_builtin += 1
                meta_ok = bool(theme.id and theme.schema and theme.tags)
                tokens_ok = bool(theme.colors and theme.typography and theme.spacing)
                inherits = theme.extends if theme.extends else "None"
                print_success(
                    f"Built-in Theme '{theme.name}': Metadata {'OK' if meta_ok else 'MISSING'}, Tokens {'OK' if tokens_ok else 'MISSING'}, Inheritance: {inherits}"
                )
            except Exception as e:
                print_error(f"Failed to load built-in theme {theme_file.name}: {e}")
        print_success(f"Validated {valid_builtin} built-in themes")

    templates = list_builtin_templates()
    if templates:
        print_success(f"Built-in templates ({len(templates)}): {', '.join(templates)}")

    print("\nDiagnostics complete.")


def cmd_validate(args):
    config_path = Path(args.config)
    print(f"Validating configuration at '{config_path}'...\n")

    if not config_path.exists():
        print_error(f"Configuration file '{config_path}' not found.")
        sys.exit(1)

    try:
        config = ConfigLoader.load_main_config(str(config_path))
        print_success("profileforge.yaml valid")

        theme_dir = config_path.parent / "themes"
        ConfigLoader.load_theme(config.active_theme, themes_dir=str(theme_dir))
        print_success(f'Theme "{config.active_theme}" exists')

        for w in config.widgets:
            if w.name in WIDGET_REGISTRY:
                print_success(f'Widget "{w.name}"')
            else:
                print(f'  X Widget "{w.name}"')
                print("\nReason:\nUnknown widget")
                print(
                    "\nDid you mean:\n" + "\n".join([f"• {k}" for k in WIDGET_REGISTRY])
                )
                sys.exit(1)

        out_dir = (
            Path(args.output)
            if args.output
            else config_path.parent / config.outputs.svg.dir
        )
        if not out_dir.exists():
            out_dir.mkdir(parents=True, exist_ok=True)
        if os.access(out_dir, os.W_OK):
            print_success("Output directory writable")
        else:
            print_error(f"Output directory '{out_dir}' is not writable.")
            sys.exit(1)

        print("\nConfiguration is 100% valid.")
    except ProfileForgeError as e:
        print_error(str(e))
        sys.exit(1)


def cmd_new(args):
    template_name = getattr(args, "template", "backend") or "backend"
    available_templates = list_builtin_templates()

    if template_name not in available_templates:
        print_error(
            f"Unknown template '{template_name}'.\n"
            f"Available templates: {', '.join(available_templates)}\n"
            f"Run 'profileforge templates list' to see details of all templates."
        )
        sys.exit(1)

    target = Path(args.name)
    if target.exists() and any(target.iterdir()):
        print_error(f"Directory '{args.name}' already exists and is not empty.")
        sys.exit(1)

    project_name = args.name.replace("-", " ").replace("_", " ").title() + " Profile"

    try:
        scaffold_template(
            template_name=template_name,
            target_dir=target,
            project_name=project_name,
        )
        print_success(
            f"Created new ProfileForge project in '{args.name}' using '{template_name}' template"
        )
        print_success(f"Config and starter widgets seeded in '{args.name}/config'")
        print(
            f"\nRun 'cd {args.name}' then 'profileforge build' to compile your profile widgets."
        )
    except Exception as e:
        print_error(f"Failed to scaffold template: {e}")
        sys.exit(1)


def cmd_init(args):
    template_name = getattr(args, "template", "backend") or "backend"
    available_templates = list_builtin_templates()

    if template_name not in available_templates:
        print_error(
            f"Unknown template '{template_name}'.\n"
            f"Available templates: {', '.join(available_templates)}\n"
            f"Run 'profileforge templates list' to see details of all templates."
        )
        sys.exit(1)

    target_dir = Path(args.directory).resolve()
    config_file = target_dir / "profileforge.yaml"
    if config_file.exists():
        print_error(f"A ProfileForge project already exists at '{target_dir}'.")
        sys.exit(1)

    project_name = getattr(args, "name", None)
    if not project_name:
        dir_name = target_dir.name
        project_name = (
            "Developer Profile"
            if dir_name in (".", "", "profileforge")
            else f"{dir_name.replace('-', ' ').replace('_', ' ').title()} Profile"
        )

    try:
        scaffold_template(
            template_name=template_name,
            target_dir=target_dir,
            project_name=project_name,
        )
        print_success(
            f"Initialized ProfileForge project in '{args.directory}' using '{template_name}' template"
        )
        print("\nRun 'profileforge build' to compile your profile widgets.")
    except Exception as e:
        print_error(f"Failed to initialize project: {e}")
        sys.exit(1)


def cmd_templates_list(args):
    print("Available ProfileForge Starter Templates:\n")
    template_ids = list_builtin_templates()
    for t_id in template_ids:
        info = get_template_info(t_id) or {}
        name = info.get("name", t_id.title())
        theme = info.get("default_theme", "github-dark")
        desc = info.get("description", "")
        widgets = ", ".join(info.get("widgets", []))
        print(f"  * {t_id:<14} {name} (Default Theme: {theme})")
        if widgets:
            print(f"    Widgets:     {widgets}")
        if desc:
            print(f"    Description: {desc}")
        print()
    print("Scaffold a new project:")
    print("  profileforge new <dir-name> --template <template-id>")
    print("  profileforge init --template <template-id>\n")


def cmd_themes_build(args):
    config_path = Path(args.config)
    try:
        if not config_path.exists():
            print_error(f"Config file not found: {args.config}")
            sys.exit(1)

        config = ConfigLoader.load_main_config(str(config_path))
        print_success("Loaded configuration")

        theme_dir = config_path.parent / "themes"
        if not theme_dir.exists():
            theme_dir = Path(__file__).parent.parent / "themes"

        gallery_dir = config_path.parent / "gallery"
        gallery_dir.mkdir(parents=True, exist_ok=True)

        # We need to render the `github_stats` widget
        from profileforge.core.models import WidgetConfig

        widget_config = WidgetConfig(name="github_stats")
        config.widgets = [widget_config]

        connectors = {}
        for name, ds_config in config.connectors_config.items():
            if name in ConnectorRegistry:
                if "root" in ds_config:
                    ds_config["root"] = str(config_path.parent / ds_config["root"])
                connectors[name] = ConnectorRegistry[name](ds_config)
        services = Services(connectors=connectors)

        if "github_stats" not in WIDGET_REGISTRY:
            print_error("Widget 'github_stats' not found in registry.")
            sys.exit(1)

        theme_files = []
        if theme_dir.exists():
            theme_files.extend(list(theme_dir.glob("*.yaml")))

        builtin_themes_dir = Path(__file__).parent.parent / "themes"
        if builtin_themes_dir.exists():
            theme_files.extend(list(builtin_themes_dir.glob("*.yaml")))

        import html as html_mod

        seen_themes = set()
        for theme_file in theme_files:
            theme_name = theme_file.stem
            if theme_name in seen_themes:
                continue
            seen_themes.add(theme_name)
            try:
                theme = ConfigLoader.load_theme(theme_name, themes_dir=str(theme_dir))

                config.active_theme = theme_name
                context = BuildContext(theme=theme, config=config, services=services)
                svg_renderer = SVGRenderer(context)

                widget = WIDGET_REGISTRY["github_stats"]()
                component_tree = widget.render_safe(context)
                LayoutEngine.calculate(component_tree)

                inner_svg = svg_renderer.render(component_tree)
                defs_block = svg_renderer.get_defs()
                total_w = component_tree.computed_width
                total_h = component_tree.computed_height

                escaped_title = html_mod.escape(f"github_stats - {theme_name}")

                svg_content = (
                    f'<svg width="{total_w}" height="{total_h}" '
                    f'viewBox="0 0 {total_w} {total_h}" '
                    f'xmlns="http://www.w3.org/2000/svg" '
                    f'role="img">\n'
                    f"  <title>{escaped_title}</title>\n"
                    f"  <desc>ProfileForge widget preview</desc>\n"
                    f"  {defs_block}\n"
                    f"  {inner_svg}\n"
                    f"</svg>"
                )

                out_file = gallery_dir / f"{theme_name}.svg"
                with open(out_file, "w", encoding="utf-8") as f:
                    f.write(svg_content)
                print_success(f"Generated gallery/{theme_name}.svg")
            except Exception as e:
                print_error(f"Failed to build gallery for theme {theme_name}: {e}")

    except ProfileForgeError as e:
        print_error(str(e))
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="ProfileForge: Open-Source GitHub Profile Engine"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Build the profile widgets")
    build_parser.add_argument(
        "--config", default="profileforge.yaml", help="Path to config file"
    )
    build_parser.add_argument(
        "--output", default=None, help="Override output directory"
    )

    subparsers.add_parser("doctor", help="Check dependencies and environment")

    init_parser = subparsers.add_parser(
        "init", help="Initialize a ProfileForge project in target directory"
    )
    init_parser.add_argument(
        "directory",
        nargs="?",
        default=".",
        help="Target directory (default: current directory)",
    )
    init_parser.add_argument(
        "--template",
        "-t",
        default="backend",
        help="Starter template to use (backend, frontend, minimal, student, opensource, ai-engineer)",
    )
    init_parser.add_argument(
        "--name", default=None, help="Custom project name override"
    )

    new_parser = subparsers.add_parser(
        "new", help="Scaffold a new ProfileForge project in a new directory"
    )
    new_parser.add_argument("name", help="Name of the new project directory")
    new_parser.add_argument(
        "--template",
        "-t",
        default="backend",
        help="Starter template to use (backend, frontend, minimal, student, opensource, ai-engineer)",
    )

    validate_parser = subparsers.add_parser(
        "validate", help="Validate a configuration file"
    )
    validate_parser.add_argument(
        "--config", default="profileforge.yaml", help="Path to config file"
    )
    validate_parser.add_argument(
        "--output", default=None, help="Output directory to check write access"
    )

    templates_parser = subparsers.add_parser("templates", help="Template commands")
    templates_subparsers = templates_parser.add_subparsers(dest="templates_command")
    templates_subparsers.add_parser(
        "list", help="List all available official starter templates"
    )

    themes_parser = subparsers.add_parser("themes", help="Theme commands")
    themes_subparsers = themes_parser.add_subparsers(
        dest="themes_command", required=True
    )
    themes_build_parser = themes_subparsers.add_parser(
        "build", help="Build theme gallery"
    )
    themes_build_parser.add_argument(
        "--config", default="profileforge.yaml", help="Path to config file"
    )

    args = parser.parse_args()

    if args.command == "build":
        cmd_build(args)
    elif args.command == "doctor":
        cmd_doctor(args)
    elif args.command == "init":
        cmd_init(args)
    elif args.command == "validate":
        cmd_validate(args)
    elif args.command == "new":
        cmd_new(args)
    elif args.command == "templates":
        if args.templates_command in ("list", None):
            cmd_templates_list(args)
        else:
            print_error(
                f"Command 'templates {args.templates_command}' is not implemented."
            )
            sys.exit(1)
    elif args.command == "themes":
        if args.themes_command == "build":
            cmd_themes_build(args)
        else:
            print_error(f"Command 'themes {args.themes_command}' is not implemented.")
            sys.exit(1)
    else:
        print_error(f"Command '{args.command}' is not implemented.")
        sys.exit(1)


if __name__ == "__main__":
    main()
